# - name: Install mysql-server package
#   dnf:
#     name: 
#       - mysql-server
#       - python3-PyMySQL
#       - mysql

- name: install percona key
  ansible.builtin.rpm_key:
    key: https://www.percona.com/downloads/RPM-GPG-KEY-percona
    state: present

# wget https://repo.percona.com/yum/percona-release-latest.noarch.rpm
# rpm -i percona-release-latest.noarch.rpm
- name: Install percona repo
  ansible.builtin.package:
    name: 'https://repo.percona.com/yum/percona-release-latest.noarch.rpm'
    state: present
    update_cache: true

- name: Update cache
  ansible.builtin.dnf: 
    update_cache: yes

# percona-release setup pxc-80
- name: percona-release setup pxc-80
  ansible.builtin.shell: echo 'y' | percona-release setup pxc-80

# dnf install percona-xtradb-cluster -y
- name: Install packages
  ansible.builtin.package:
    name: 
      - percona-xtradb-cluster
      - python3-PyMySQL
    state: latest

# systemctl restart percona
- name: Restart Percona service
  ansible.builtin.service:
    name: mysql
    state: restarted

- name: Get temporary mysql root password
  ansible.builtin.shell: grep 'temporary password' /var/log/mysqld.log | awk '{print $NF}' | tail -n 1
  register: temp_mysql_root_password

#- ansible.builtin.debug: 
#    var: temp_mysql_root_password.stdout

- ansible.builtin.debug: 
  msg: "{{ temp_mysql_root_password.stdout }}"

- name: Save root password in .my.cnf
  template:
    src: root-my_empty.cnf.j2
    dest: /root/.my.cnf
    owner: root
    mode: '0600'

- name: start and enable mysql service
  service:
    name: mysqld
    state: started
    enabled: yes

- name: Sets the root password
  mysql_user:
    # login_user: root
    # login_password: ""
    name: "{{ mysql_root_user }}"
    password: "{{ mysql_root_password }}"
    # login_unix_socket: /var/run/mysqld/mysqld.sock

- name: Save root password in .my.cnf
  template:
    src: root-my.cnf.j2
    dest: /root/.my.cnf
    owner: root
    mode: '0600'

- name: creating wp_db
  mysql_db:
    name: "{{db_name}}"
    login_host: "localhost"
    login_user: "{{ mysql_root_user }}"
    login_password: "{{ mysql_root_password }}"
    state: present

- name: creating mysql user (medium_post)
  mysql_user:
    name: "{{db_user}}"
    password: "{{db_pass}}"
    priv: 'wp_db.*:ALL'
    host: '%'
    state: present

# - name: Enable remote login to mysql
#   lineinfile:
#     path: /etc/mysql/mysql.conf.d/mysqld.cnf
#     regexp: '^bind-address'
#     line: 'bind-address = 0.0.0.0'
#     backup: yes

- name: Restart mysql
  service:
    name: mysqld
    state: restarted