- name: Install targetcli
  yum:
    name:
      - targetcli
    state: present

- name: Run targetcli configure
  ansible.builtin.command: "{{ item }}"
  with_items:
    - targetcli /backstores/block create disk01 /dev/vdb
    - targetcli /iscsi create {{ iqn_server }}
    - targetcli /iscsi/{{ iqn_server }}/tpg1/luns create /backstores/block/disk01 lun=1
    - targetcli /iscsi/{{ iqn_server }}/tpg1/acls create {{ iqn_pcs1 }}
    - targetcli /iscsi/{{ iqn_server }}/tpg1/acls create {{ iqn_pcs2 }}
    - targetcli /iscsi/{{ iqn_server }}/tpg1/acls create {{ iqn_pcs3 }}

# - name: This command will change the working directory to somedir/
#   ansible.builtin.shell:
#     cmd: ls -l | grep log
#     chdir: somedir/