- name: apt-get update
  apt:
    update_cache: yes
- name: Install targetcli
  apt:
    name:
      - targetcli-fb
    state: present
# - name: This command will change the working directory to somedir/
#   ansible.builtin.shell:
#     cmd: ls -l | grep log
#     chdir: somedir/
- name: Run targetcli configure
  ansible.builtin.command: "{{ item }}"
  with_items:
    - targetcli /backstores/block create disk01 /dev/vdb
    - targetcli /iscsi create iqn.2023-11.ru.otus:storage.target00
    - targetcli /iscsi/iqn.2023-11.ru.otus:storage.target00/tpg1/luns create /backstores/block/disk01 lun=1
    - targetcli /iscsi/iqn.2023-11.ru.otus:storage.target00/tpg1/acls create iqn.1993-08.org.debian:01:84cdc7f825a1