- name: Install targetcli
  yum:
    name:
      - targetcli
    state: present

- name: Gather targetcli status
  command: "targetcli /backstores/block/disk01 info"
  register: targetcli_status
  ignore_errors: true

- name: Run targetcli configure
  ansible.builtin.command: "{{ item }}"
  with_items:
    - targetcli /backstores/block create disk01 /dev/vdb
    - targetcli /iscsi create {{ iqn_server }}
    - targetcli /iscsi/{{ iqn_server }}/tpg1/luns create /backstores/block/disk01 lun=1
    - targetcli /iscsi/{{ iqn_server }}/tpg1/acls create {{ iqn_backend1 }}
    - targetcli /iscsi/{{ iqn_server }}/tpg1/acls create {{ iqn_backend2 }}
  when: targetcli_status.rc | int != 0

# - name: This command will change the working directory to somedir/
#   ansible.builtin.shell:
#     cmd: ls -l | grep log
#     chdir: somedir/