---
- name: Install Chrony
  hosts: all
  gather_facts: false
  become: true
  #serial: 5
  roles:
    - chrony

- name: install targetcli, create lun
  hosts: iscsi_srv
  gather_facts: false
  become: yes
  roles:
  - targetcli

- name: install iscsi-client
  hosts: backend_hosts
  gather_facts: false
  become: yes
  roles:
  - iscsi-client

- name: install ha-cluster
  hosts: backend_hosts
  gather_facts: false
  become: yes
  roles:
  - ha-cluster

- name: install-mysql
  hosts: db_hosts
  gather_facts: false
  become: yes
  roles:
  - db

- name: install-wordpress
  hosts: backend_hosts
  gather_facts: false
  become: yes
  roles:
  - wordpress
