---
- name: Install Chrony
  hosts: all
  gather_facts: false
  become: true
  roles:
  - chrony

# - name: install-wordpress
#   hosts: backend_hosts
#   gather_facts: false
#   become: yes
#   roles:
#   - wordpress

- name: install pgsql cluster
  hosts: db_hosts
  #gather_facts: false
  become: yes
  roles:
  - pgsql-cluster